# grafana-docker-compose.yaml

version: '3'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana-dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: dashboarduser
      GF_SECURITY_ADMIN_PASSWORD: dashboardpassword
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 500ms
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage:
    driver: local


networks:
  default:
    name: mlops-network