{
 "title": "Machine Dash",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(air_temperature) AS mean_air_temperature, \r\n       AVG(process_temperature) AS mean_process_temperature, AVG(rotational_speed) AS mean_rotational_speed, AVG(torque) AS mean_torqe, AVG(tool_wear) AS mean_tool_wear, \"timestamp\"\r\nFROM machine_data\r\nWHERE \"timestamp\" < NOW()\r\nGROUP by timestamp\r\norder by timestamp desc\r\nLIMIT 500;\r\n"
    }
   ]
  },
  {
   "title": "Total Failure with Machine Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    machine_type,\r\n    SUM(twf) AS total_twf,\r\n    SUM(hdf) AS total_hdf,\r\n    SUM(pwf) AS total_pwf,\r\n    SUM(osf) AS total_osf,\r\n    SUM(rnf) AS total_rnf,\r\n    SUM(machine_failure) AS total_failire\r\nFROM (\r\n    SELECT \"timestamp\", machine_type, twf, hdf, pwf, osf, rnf, machine_failure\r\n    FROM machine_data\r\n    WHERE \"timestamp\" < NOW()\r\n    ORDER BY \"timestamp\" DESC\r\n    LIMIT 10000\r\n) AS subquery\r\nGROUP BY machine_type;"
    }
   ]
  },
  {
   "title": "Air temperature [K]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT air_temperature, \"timestamp\"\r\nFROM machine_data\r\nWHERE \"timestamp\" < NOW()\r\norder by timestamp desc\r\nLIMIT 5000;"
    }
   ]
  },
  {
   "title": "Process Temperature [K]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT process_temperature, \"timestamp\" FROM machine_data\r\nWHERE \"timestamp\" < NOW()\r\norder by timestamp desc\r\nLIMIT 5000;"
    }
   ]
  },
  {
   "title": "Rotational Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rotational_speed, \"timestamp\" FROM machine_data\r\nWHERE \"timestamp\" < NOW()\r\norder by timestamp desc\r\nLIMIT 5000;"
    }
   ]
  },
  {
   "title": "Torque",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT torque, \"timestamp\" FROM machine_data\r\nWHERE \"timestamp\" < NOW()\r\norder by timestamp desc\r\nLIMIT 5000;"
    }
   ]
  }
 ]
}